# 工作流名称
name: Build Flutter Android APK
# 触发规则：推送代码 / 手动点Run workflow 均可运行
on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # 开启手动运行按钮（关键）
jobs:
  build-apk:
    runs-on: ubuntu-latest # 云端Ubuntu服务器编译
    steps:
      # 1.拉取源码
      - name: Checkout code
        uses: actions/checkout@v4
      # 2.配置Flutter环境
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # 可根据项目实际Flutter版本修改
          channel: stable
          cache: true # 缓存依赖，下次打包更快
      # 3.拉取项目依赖
      - name: Install dependencies
        run: flutter pub get
      # 4.编译Release正式APK（arm64主流手机通用）
      - name: Build Release APK
        run: flutter build apk --release --target-platform=android-arm64
      # 5.把编译好的APK打包上传，运行完成可下载
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
